# Generated by Django 2.2.6 on 2019-10-12 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=30)),
                ('primary_name_server', models.CharField(max_length=30)),
                ('child_domain', models.CharField(max_length=30)),
                ('parent_domain', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=30)),
                ('domain', models.CharField(max_length=30)),
            ],
        ),

    ]
